- name: Add repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install DOCKER and etc
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.3/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: a+x

- name: Enable DOCKER
  systemd:
    name: docker
    enabled: yes

- name: Systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: Add users to the Docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: DOCKER start
  systemd:
    state: restarted
    name: docker
